// backend/models/Quiz.js
// Stores quiz questions generated by AI or created manually

const mongoose = require('mongoose');

const quizSchema = new mongoose.Schema({
  // Quiz title
  title: {
    type: String,
    required: true,
    trim: true
  },
  
  // Description/topic
  description: {
    type: String,
    trim: true
  },
  
  // Teacher who created this quiz
  creator: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  // Group/session this quiz belongs to
  group: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Group',
    required: true
  },
  
  // How quiz was created
  source: {
    type: String,
    enum: ['ai', 'manual', 'template'],
    default: 'ai'
  },
  
  // If AI generated, what was the input
  aiSource: {
    type: {
      type: String,
      enum: ['text', 'image', 'pdf', 'url']
    },
    content: String // URL or text content
  },
  
  // Array of questions
  questions: [{
    questionText: {
      type: String,
      required: true
    },

    // Determines how the question is rendered and evaluated
    questionType: {
      type: String,
      enum: ['multiple_choice', 'fill_in_blank', 'true_false', 'multiple_select'],
      default: 'multiple_choice'
    },

    // Options array — empty for fill_in_blank
    options: [{ type: String }],

    // Correct answer: Number (MC/TF), String (FIB), Number[] (multiple_select)
    correctAnswer: {
      type: mongoose.Schema.Types.Mixed,
      required: true
    },

    // Explanation (optional)
    explanation: String,

    // Points for this question
    points: {
      type: Number,
      default: 10
    },

    // Time limit in seconds
    timeLimit: {
      type: Number,
      default: 30
    },

    difficulty: {
      type: String,
      enum: ['easy', 'medium', 'hard', 'expert'],
      default: 'medium'
    }
  }],
  
  // Quiz settings
  settings: {
    // Total time limit for entire quiz (minutes)
    totalTimeLimit: {
      type: Number,
      default: 0 // 0 = no limit
    },
    
    // Shuffle questions?
    shuffleQuestions: {
      type: Boolean,
      default: false
    },
    
    // Shuffle options?
    shuffleOptions: {
      type: Boolean,
      default: true
    },
    
    // Show correct answers after each question?
    showCorrectAnswer: {
      type: Boolean,
      default: true
    },
    
    // Show leaderboard after each question?
    showLeaderboard: {
      type: Boolean,
      default: true
    },
    
    // Allow late joins?
    allowLateJoin: {
      type: Boolean,
      default: true
    },

    // ✅ NEW (Phase 3 — TEAM_MODE_DESIGN.md §2/§9.1): Individual vs Team Battle.
    // 'random_teams' | 'school_house' | 'custom_teams' are reserved enum values for
    // Phase 4 — the schema supports them now so no later migration is needed, but only
    // 'individual' and 'team_battle' have real gameplay logic behind them so far.
    quizMode: {
      type: String,
      enum: ['individual', 'team_battle', 'random_teams', 'school_house', 'custom_teams'],
      default: 'individual'
    },

    // Team setup — only meaningful when quizMode !== 'individual'
    teamMode: {
      teamCount: { type: Number, min: 2, max: 4 },
      // Teacher-defined teams. teamId is derived from name (see quiz-socket-handlers.js) —
      // no separate id scheme needed since team names are already required to be unique
      // within a quiz.
      teams: [{
        name:  { type: String, trim: true },
        color: { type: String, trim: true },
        icon:  { type: String, trim: true }
      }],
      // If false, the teacher assigns teams instead of students picking their own
      allowStudentChoice: { type: Boolean, default: true },
      // Keeps team sizes within 1 of each other by rejecting a pick that would overload a team
      autoBalance: { type: Boolean, default: true },
      // Freezes team assignment the moment the teacher starts the quiz — a late joiner
      // (only possible if settings.allowLateJoin is also true) is auto-assigned to
      // whichever team currently has the fewest members
      lockOnStart: { type: Boolean, default: true }
    },

    // End-of-quiz awards — individual-mode awards (fastestThinker/bestAccuracy/
    // longestStreak/mostImproved) already compute unconditionally as of Phase 2;
    // these flags exist for the future teacher-facing on/off toggles (Phase 3.6+),
    // not yet read by the gameplay/finalization code — see the Phase 2 checklist note
    // about not shipping toggles with no code path behind them; teamSpirit IS already
    // wired up (Phase 3.5) since it only makes sense in team mode, unlike the rest.
    awards: {
      mvp:            { type: Boolean, default: true },
      fastestThinker: { type: Boolean, default: true },
      bestAccuracy:   { type: Boolean, default: true },
      longestStreak:  { type: Boolean, default: true },
      mostImproved:   { type: Boolean, default: false },
      teamSpirit:     { type: Boolean, default: true }
    }
  },

  // Quiz status
  status: {
    type: String,
    enum: ['draft', 'ready', 'archived'],
    default: 'draft'
  },
  
  // Times this quiz was used
  timesUsed: {
    type: Number,
    default: 0
  },
  
  // Average score across all sessions
  averageScore: {
    type: Number,
    default: 0
  }
  
}, {
  timestamps: true
});

// ========================================
// METHODS
// ========================================

// Calculate total points
quizSchema.methods.getTotalPoints = function() {
  return this.questions.reduce((sum, q) => sum + (q.points || 10), 0);
};

// Get question count
quizSchema.methods.getQuestionCount = function() {
  return this.questions.length;
};

// Shuffle array helper
quizSchema.methods.shuffleArray = function(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

// Get quiz for session (apply shuffling)
quizSchema.methods.getSessionQuiz = function() {
  let questions = [...this.questions];
  
  // Shuffle questions if enabled
  if (this.settings.shuffleQuestions) {
    questions = this.shuffleArray(questions);
  }
  
  // Shuffle options if enabled — skip for fill_in_blank (no options, correctAnswer is string)
  if (this.settings.shuffleOptions) {
    questions = questions.map(q => {
      if (q.questionType === 'fill_in_blank' || !q.options || q.options.length === 0) {
        return q.toObject ? q.toObject() : q;
      }
      const options = [...q.options];
      const correctOption = options[q.correctAnswer];
      const shuffledOptions = this.shuffleArray(options);
      const newCorrectIndex = shuffledOptions.indexOf(correctOption);

      return {
        ...q.toObject(),
        options: shuffledOptions,
        correctAnswer: newCorrectIndex
      };
    });
  }
  
  return questions;
};

// Update average score
quizSchema.methods.updateAverageScore = async function(sessionScore) {
  this.timesUsed += 1;
  this.averageScore = ((this.averageScore * (this.timesUsed - 1)) + sessionScore) / this.timesUsed;
  await this.save();
};

// ========================================
// INDEXES
// ========================================

quizSchema.index({ creator: 1, createdAt: -1 });
quizSchema.index({ group: 1 });
quizSchema.index({ status: 1 });

module.exports = mongoose.model('Quiz', quizSchema);